In [1]:
import numpy as np
arry=np.array([0,1,23],np.int64)
arry
#creating an array using numpy with space as 64
#can also creat multi dymnetional array

array([ 0,  1, 23], dtype=int64)

In [2]:
arry[0]
#access to elements using inndex

0

In [3]:
#arry2=np.array([0,2352565626,4,6], np.int32)
#arry2
#as the value is greater then 32 bit it is giving an error

In [4]:
arry[1]=10
arry
#updating the arrying

array([ 0, 10, 23], dtype=int64)

In [5]:
arry.shape

(3,)

In [6]:
arry.size

3

In [7]:
arry.dtype

dtype('int64')

In [8]:
zero=np.zeros((2,3))
zero
#gives me a zero martix to given dimensions of type flot64

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
rng=np.arange(20)
rng
#arange gives the arry of the number in the range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
larry=np.linspace(1,5,6)
larry
#linspace give an arry of the number with equal intervals 1 to 5 with 6 eqal divison

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [11]:
emp=np.empty(5)
emp
#give an empty arry
emp2=np.empty((5,5))
emp2
#gives 2 d empty array

array([[1.46807766e-311, 7.50979782e-322, 0.00000000e+000,
        0.00000000e+000, 1.89146896e-307],
       [1.16095484e-028, 1.44649777e-012, 4.82679021e+233,
        9.91233782e-096, 1.96098951e+243],
       [1.06318457e+248, 2.49970340e+262, 1.96086579e+243,
        3.17095857e+180, 2.19526213e-152],
       [5.22373794e+257, 1.14448785e+243, 2.31859154e+251,
        1.49005471e+195, 1.69337966e-152],
       [7.79956599e-143, 2.91237123e+257, 4.71294503e+257,
        1.03412617e+295, 2.56765117e-312]])

In [12]:
ide=np.identity(6)
ide
#gives identy matrix of 6X6

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [13]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [14]:
arr=arr.reshape(3,33)
arr
#used to resahpe the matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [15]:
arr=arr.ravel()
arr
#comes back to orignal form or into 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [16]:
ax=np.array([[1,2,3],[4,5,6],[7,8,9]])
ax

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
ax.sum(axis=0)
#axis=0 menas the rows of the matrix

array([12, 15, 18])

In [18]:
ax.sum(axis=1)
#axis=1 means col

array([ 6, 15, 24])

In [19]:
ax.T
#gives traspose 

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
ax.ndim
#gives dimension

2

In [21]:
ax.nbytes
#gives the storage value

36

In [22]:
ar=np.array([1,25,2646,12])
ar.argmax()
#gives the index where the max elemnt is present

2

In [23]:
ar.argmin()
#give min index

0

In [24]:
ar.argsort()
#gives the index in which if places the array will be sorted

array([0, 3, 1, 2], dtype=int64)